package com.example.personal.sutdbookingapp;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.Set;


public class DBstudent_table {
    @DynamoDBTable(tableName = "Student_table")
    public static class AWS {
        private DynamoDBMapper dynamoDBMapper;
        private String student_id ="1234";
        private String password="123";

        @DynamoDBHashKey(attributeName = "Student_id")
        @DynamoDBAttribute(attributeName = "student_id")
        @DynamoDBAutoGeneratedKey
        public void setStudent_id(final String _userId) {
            this.student_id = student_id;       // student_id & password get from login page i.e. user input
        }

        public String getStudent_id() {
            System.out.println(student_id);
            return student_id;
        }


        @DynamoDBRangeKey(attributeName = "password")
        @DynamoDBAttribute(attributeName = "password")
        public void setPassword(final String password) {
            this.password = password;
        }

        public String getPassword() {
            System.out.println(password);
            return password;

        }

//        public void readNews() {
//            new Thread(new Runnable() {
//                @Override
//                public void run() {
//
//                    NewsDO newsItem = dynamoDBMapper.load(
//                            NewsDO.class,
//                            ida,
//                            "Article1");
//
//                    // Item read
//                    //Log.d("News Item:", newsItem.toString());
//                }
//            }).start();
//        }
//
//        public void updateNews() {
//            final NewsDO newsItem = new NewsDO();
//
//            newsItem.setUserId(ida);
//
//            newsItem.setArticleId("Article1");
//            newsItem.setContent("This is the updated content.");
//
//            new Thread(new Runnable() {
//                @Override
//                public void run() {
//
//                    dynamoDBMapper.save(newsItem);
//
//                    // Item updated
//                }
//            }).start();
//        }
//
//        public void deleteNews() {
//            new Thread(new Runnable() {
//                @Override
//                public void run() {
//
//                    NewsDO newsItem = new NewsDO();
//
//                    newsItem.setUserId(ida);    //partition key
//
//                    newsItem.setArticleId("Article1");  //range (sort) key
//
//                    dynamoDBMapper.delete(newsItem);
//
//                    // Item deleted
//                }
//            }).start();
//        }

    }


//    public static void main(String args[]) {
//        AWS aws = new AWS();
//        aws.getStudent_id();
//        aws.getPassword();
//    }
}
