package com.example.personal.sutdbookingapp;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBIndexRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBRangeKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

import java.util.List;
import java.util.Map;
import java.util.Set;

@DynamoDBTable(tableName = "sutdbookingapp-mobilehub-1464484747-StudentTable")

public class NewsDO {
    private String _userId;
    private String _password;
//    private String _author;
//    private String _category;
    private String _name;
//    private Double _creationDate;
//    private Set<String> _keywords;
//    private String _title;

    @DynamoDBHashKey(attributeName = "userId")
    @DynamoDBAttribute(attributeName = "userId")
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return _userId;
    }

    public void setUserId(final String _userId) {
        this._userId = _userId;
    }
    @DynamoDBRangeKey(attributeName = "password")
    @DynamoDBAttribute(attributeName = "password")
    public String getPassword() {
        return _password;
    }

    public void setPassword(final String _password) {
        this._password = _password;
    }
//    @DynamoDBIndexHashKey(attributeName = "author", globalSecondaryIndexName = "Authors")
//    public String getAuthor() {
//        return _author;
//    }
//
//    public void setAuthor(final String _author) {
//        this._author = _author;
//    }
//    @DynamoDBIndexHashKey(attributeName = "category", globalSecondaryIndexName = "Categories")
//    public String getCategory() {
//        return _category;
//    }
//
//    public void setCategory(final String _category) {
//        this._category = _category;
//    }
//    @DynamoDBAttribute(attributeName = "content")
//    public String getContent() {
//        return _name;
//    }
//
//    public void setContent(final String _name) {
//        this._name = _name;
//    }
//    @DynamoDBIndexRangeKey(attributeName = "creationDate", globalSecondaryIndexName = "Categories")
//    public Double getCreationDate() {
//        return _creationDate;
//    }
//
//    public void setCreationDate(final Double _creationDate) {
//        this._creationDate = _creationDate;
//    }
//    @DynamoDBAttribute(attributeName = "keywords")
//    public Set<String> getKeywords() {
//        return _keywords;
//    }
//
//    public void setKeywords(final Set<String> _keywords) {
//        this._keywords = _keywords;
//    }
//    @DynamoDBAttribute(attributeName = "title")
//    public String getTitle() {
//        return _title;
//    }
//
//    public void setTitle(final String _title) {
//        this._title = _title;
//    }

}
